windows_container:
  image: cirrusci/windowsservercore:2019
  cpu: 4
  memory: 12G

task:
  script:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
